-- 09 — FPL clubs and fixture import
-- Run once in the Supabase SQL Editor after pot_gameweek_schedule.sql.

create table if not exists public.football_teams (
  id bigint generated by default as identity primary key,
  fpl_team_id integer not null unique,
  code integer not null,
  name text not null,
  short_name text not null,
  emblem_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.football_fixtures (
  id bigint generated by default as identity primary key,
  fpl_fixture_id integer not null unique,
  season text not null,
  gameweek_number integer check (gameweek_number between 1 and 38),
  kickoff_at timestamptz,
  home_team_id bigint not null references public.football_teams(id),
  away_team_id bigint not null references public.football_teams(id),
  home_score integer,
  away_score integer,
  started boolean not null default false,
  finished boolean not null default false,
  provisional_start_time boolean not null default false,
  updated_at timestamptz not null default now(),
  check (home_team_id <> away_team_id)
);

create index if not exists football_fixtures_gameweek_idx on public.football_fixtures (season,gameweek_number,kickoff_at);
alter table public.football_teams enable row level security;
alter table public.football_fixtures enable row level security;
grant select on table public.football_teams,public.football_fixtures to authenticated;

drop policy if exists "Signed-in players can view football teams" on public.football_teams;
create policy "Signed-in players can view football teams" on public.football_teams for select to authenticated using (true);
drop policy if exists "Signed-in players can view football fixtures" on public.football_fixtures;
create policy "Signed-in players can view football fixtures" on public.football_fixtures for select to authenticated using (true);

create or replace function public.sync_fpl_data(selected_season text,fpl_teams jsonb,fpl_fixtures jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare team_count integer;
declare fixture_count integer;
begin
  if not (select public.is_current_user_admin()) then raise exception 'Administrator access required'; end if;
  if jsonb_typeof(fpl_teams) <> 'array' or jsonb_typeof(fpl_fixtures) <> 'array' then raise exception 'Invalid FPL data'; end if;

  insert into public.football_teams (fpl_team_id,code,name,short_name,emblem_url,updated_at)
  select (team ->> 'id')::integer,(team ->> 'code')::integer,team ->> 'name',team ->> 'short_name',
    'https://resources.premierleague.com/premierleague/badges/100/t' || (team ->> 'code') || '.png',now()
  from jsonb_array_elements(fpl_teams) as supplied(team)
  on conflict (fpl_team_id) do update set code=excluded.code,name=excluded.name,short_name=excluded.short_name,emblem_url=excluded.emblem_url,updated_at=now();
  get diagnostics team_count = row_count;

  insert into public.football_fixtures (fpl_fixture_id,season,gameweek_number,kickoff_at,home_team_id,away_team_id,home_score,away_score,started,finished,provisional_start_time,updated_at)
  select (fixture ->> 'id')::integer,trim(selected_season),nullif(fixture ->> 'event','')::integer,
    nullif(fixture ->> 'kickoff_time','')::timestamptz,home.id,away.id,
    nullif(fixture ->> 'team_h_score','')::integer,nullif(fixture ->> 'team_a_score','')::integer,
    coalesce((fixture ->> 'started')::boolean,false),coalesce((fixture ->> 'finished')::boolean,false),
    coalesce((fixture ->> 'provisional_start_time')::boolean,false),now()
  from jsonb_array_elements(fpl_fixtures) as supplied(fixture)
  join public.football_teams home on home.fpl_team_id=(fixture ->> 'team_h')::integer
  join public.football_teams away on away.fpl_team_id=(fixture ->> 'team_a')::integer
  on conflict (fpl_fixture_id) do update set season=excluded.season,gameweek_number=excluded.gameweek_number,kickoff_at=excluded.kickoff_at,
    home_team_id=excluded.home_team_id,away_team_id=excluded.away_team_id,home_score=excluded.home_score,away_score=excluded.away_score,
    started=excluded.started,finished=excluded.finished,provisional_start_time=excluded.provisional_start_time,updated_at=now();
  get diagnostics fixture_count = row_count;
  return jsonb_build_object('teams',team_count,'fixtures',fixture_count,'synced_at',now());
end;
$$;
revoke all on function public.sync_fpl_data(text,jsonb,jsonb) from public;
grant execute on function public.sync_fpl_data(text,jsonb,jsonb) to authenticated;

create or replace view public.football_team_form with (security_invoker = true) as
with results as (
  select home_team_id as team_id,kickoff_at,case when home_score>away_score then 'W' when home_score=away_score then 'D' else 'L' end as result
  from public.football_fixtures where finished and home_score is not null and away_score is not null
  union all
  select away_team_id as team_id,kickoff_at,case when away_score>home_score then 'W' when away_score=home_score then 'D' else 'L' end as result
  from public.football_fixtures where finished and home_score is not null and away_score is not null
), ranked as (select *,row_number() over (partition by team_id order by kickoff_at desc) as result_number from results)
select team_id,array_agg(result order by kickoff_at desc) as last_five from ranked where result_number<=5 group by team_id;
grant select on public.football_team_form to authenticated;
