-- 10 — Player fixture selection and locked picks
-- Run once in the Supabase SQL Editor after fpl_fixture_setup.sql.

create table if not exists public.player_picks (
  id bigint generated by default as identity primary key,
  pot_id uuid not null references public.pots(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  gameweek_number integer not null check (gameweek_number between 1 and 38),
  fixture_id bigint not null references public.football_fixtures(id),
  team_id bigint not null references public.football_teams(id),
  selection_source text not null default 'manual' check (selection_source in ('manual','random','admin')),
  outcome text not null default 'pending' check (outcome in ('pending','won','lost','postponed')),
  confirmed_at timestamptz not null default now(),
  unique (pot_id,player_id,gameweek_number),
  unique (pot_id,player_id,team_id)
);

alter table public.player_picks enable row level security;
grant select on table public.player_picks to authenticated;

drop policy if exists "Players can view their own picks" on public.player_picks;
create policy "Players can view their own picks" on public.player_picks for select to authenticated
using (player_id = (select auth.uid()));

drop policy if exists "Admins can view every pick" on public.player_picks;
create policy "Admins can view every pick" on public.player_picks for select to authenticated
using ((select public.is_current_user_admin()));

create or replace function public.get_pot_selection(selected_pot_id uuid)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare membership public.pot_players%rowtype;
declare selected_gameweek integer;
declare saved_pick jsonb;
declare fixture_options jsonb;
declare remaining_teams jsonb;
begin
  select * into membership from public.pot_players
  where pot_id=selected_pot_id and player_id=(select auth.uid());
  if not found then raise exception 'You are not assigned to this pot'; end if;

  select pick.gameweek_number into selected_gameweek
  from public.player_picks pick
  where pick.pot_id=selected_pot_id and pick.player_id=(select auth.uid()) and pick.outcome='pending'
  order by pick.gameweek_number desc limit 1;

  if selected_gameweek is null then
    select gameweek.gameweek_number into selected_gameweek
    from public.pot_gameweeks gameweek
    join public.pots pot on pot.id=gameweek.pot_id
    where gameweek.pot_id=selected_pot_id
      and exists (
        select 1 from public.football_fixtures fixture
        where fixture.season=pot.season and fixture.gameweek_number=gameweek.gameweek_number
          and fixture.kickoff_at>now() and not fixture.finished
      )
    order by gameweek.gameweek_number limit 1;
  end if;

  select jsonb_build_object(
    'id',pick.id,'gameweek_number',pick.gameweek_number,'team_id',pick.team_id,
    'fixture_id',pick.fixture_id,'outcome',pick.outcome,'confirmed_at',pick.confirmed_at,
    'team_name',team.name,'emblem_url',team.emblem_url,
    'home_name',home.name,'away_name',away.name,'kickoff_at',fixture.kickoff_at
  ) into saved_pick
  from public.player_picks pick
  join public.football_teams team on team.id=pick.team_id
  join public.football_fixtures fixture on fixture.id=pick.fixture_id
  join public.football_teams home on home.id=fixture.home_team_id
  join public.football_teams away on away.id=fixture.away_team_id
  where pick.pot_id=selected_pot_id and pick.player_id=(select auth.uid())
    and pick.gameweek_number=selected_gameweek;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id',fixture.id,'gameweek_number',fixture.gameweek_number,'kickoff_at',fixture.kickoff_at,
    'started',fixture.started,'finished',fixture.finished,
    'home_score',fixture.home_score,'away_score',fixture.away_score,
    'home_team',jsonb_build_object('id',home.id,'name',home.name,'short_name',home.short_name,'emblem_url',home.emblem_url,
      'form',coalesce((select to_jsonb(form.last_five) from public.football_team_form form where form.team_id=home.id),'[]'::jsonb),
      'available',not exists(select 1 from public.player_picks used where used.pot_id=selected_pot_id and used.player_id=(select auth.uid()) and used.team_id=home.id)),
    'away_team',jsonb_build_object('id',away.id,'name',away.name,'short_name',away.short_name,'emblem_url',away.emblem_url,
      'form',coalesce((select to_jsonb(form.last_five) from public.football_team_form form where form.team_id=away.id),'[]'::jsonb),
      'available',not exists(select 1 from public.player_picks used where used.pot_id=selected_pot_id and used.player_id=(select auth.uid()) and used.team_id=away.id))
  ) order by fixture.kickoff_at),'[]'::jsonb) into fixture_options
  from public.football_fixtures fixture
  join public.pots pot on pot.id=selected_pot_id and pot.season=fixture.season
  join public.football_teams home on home.id=fixture.home_team_id
  join public.football_teams away on away.id=fixture.away_team_id
  where fixture.gameweek_number=selected_gameweek;

  select coalesce(jsonb_agg(jsonb_build_object('id',team.id,'name',team.name,'short_name',team.short_name,'emblem_url',team.emblem_url) order by team.name),'[]'::jsonb)
  into remaining_teams from public.football_teams team
  where not exists(select 1 from public.player_picks used where used.pot_id=selected_pot_id and used.player_id=(select auth.uid()) and used.team_id=team.id);

  return jsonb_build_object(
    'gameweek_number',selected_gameweek,'payment_status',membership.payment_status,
    'player_status',membership.player_status,'pick',saved_pick,
    'fixtures',fixture_options,'remaining_teams',remaining_teams
  );
end;
$$;
revoke all on function public.get_pot_selection(uuid) from public;
grant execute on function public.get_pot_selection(uuid) to authenticated;

create or replace function public.confirm_team_pick(selected_pot_id uuid,selected_fixture_id bigint,selected_team_id bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare membership public.pot_players%rowtype;
declare fixture public.football_fixtures%rowtype;
begin
  select * into membership from public.pot_players
  where pot_id=selected_pot_id and player_id=(select auth.uid());
  if not found then raise exception 'You are not assigned to this pot'; end if;
  if membership.player_status<>'active' then raise exception 'You are not active in this pot'; end if;
  if membership.payment_status<>'paid' then raise exception 'Your entry payment must be confirmed before selecting a team'; end if;
  if not exists(select 1 from public.profiles where id=(select auth.uid()) and approved) then raise exception 'Your account is awaiting approval'; end if;

  select football_fixture.* into fixture from public.football_fixtures football_fixture
  join public.pots pot on pot.id=selected_pot_id and pot.season=football_fixture.season
  where football_fixture.id=selected_fixture_id;
  if not found then raise exception 'Fixture not found for this pot'; end if;
  if fixture.gameweek_number is null or not exists(select 1 from public.pot_gameweeks where pot_id=selected_pot_id and gameweek_number=fixture.gameweek_number) then raise exception 'This gameweek is not part of the pot'; end if;
  if fixture.kickoff_at is null or fixture.kickoff_at<=now() or fixture.started or fixture.finished then raise exception 'That fixture has already started or is unavailable'; end if;
  if selected_team_id not in (fixture.home_team_id,fixture.away_team_id) then raise exception 'Select a team playing in this fixture'; end if;
  if exists(select 1 from public.player_picks where pot_id=selected_pot_id and player_id=(select auth.uid()) and gameweek_number=fixture.gameweek_number) then raise exception 'Your pick for this gameweek is already locked'; end if;
  if exists(select 1 from public.player_picks where pot_id=selected_pot_id and player_id=(select auth.uid()) and team_id=selected_team_id) then raise exception 'You have already used that team in this pot'; end if;

  insert into public.player_picks (pot_id,player_id,gameweek_number,fixture_id,team_id)
  values (selected_pot_id,(select auth.uid()),fixture.gameweek_number,selected_fixture_id,selected_team_id);
end;
$$;
revoke all on function public.confirm_team_pick(uuid,bigint,bigint) from public;
grant execute on function public.confirm_team_pick(uuid,bigint,bigint) to authenticated;
