import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const loading=document.querySelector("#admin-loading"),denied=document.querySelector("#admin-denied"),content=document.querySelector("#admin-content"),playerList=document.querySelector("#player-list"),playerCount=document.querySelector("#player-count"),countLabel=document.querySelector("#count-label"),adminTitle=document.querySelector("#admin-title"),message=document.querySelector("#admin-message"),signOutButton=document.querySelector("#sign-out"),playersView=document.querySelector("#players-view"),potsView=document.querySelector("#pots-view"),fixturesView=document.querySelector("#fixtures-view"),potForm=document.querySelector("#pot-form"),showPotFormButton=document.querySelector("#show-pot-form"),cancelPotButton=document.querySelector("#cancel-pot"),gameweekGrid=document.querySelector("#gameweek-grid"),potPlayerOptions=document.querySelector("#pot-player-options"),potList=document.querySelector("#pot-list"),syncFplButton=document.querySelector("#sync-fpl"),fixtureList=document.querySelector("#fixture-list"),fixtureSyncDetail=document.querySelector("#fixture-sync-detail");
const CURRENT_SEASON="2026/27";
let allPlayers=[];
const playerName=player=>[player.first_name,player.last_name].filter(Boolean).join(" ")||player.display_name||"Unnamed player";
function showDenied(){loading.hidden=true;content.hidden=true;denied.hidden=false}
function renderPlayers(players){
  playerCount.textContent=players.length;playerList.replaceChildren();
  if(!players.length){const empty=document.createElement("p");empty.className="empty-list";empty.textContent="No players have registered yet.";playerList.append(empty);return}
  players.forEach(player=>{
    const row=document.createElement("article");row.className="player-row";
    const details=document.createElement("div");details.className="player-details";
    const name=document.createElement("h2");name.textContent=playerName(player);
    const email=document.createElement("p");email.textContent=player.email;
    const joined=document.createElement("small");joined.textContent=`Joined ${new Date(player.created_at).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})}`;details.append(name,email,joined);
    const controls=document.createElement("div");controls.className="player-controls";
    const status=document.createElement("span");status.className=`status ${player.approved?"approved":"pending"}`;status.textContent=player.approved?"Approved":"Waiting";
    const button=document.createElement("button");button.className=`approval-button ${player.approved?"revoke":"approve"}`;button.type="button";button.textContent=player.approved?"Revoke access":"Approve player";button.addEventListener("click",()=>setApproval(player,!player.approved,button));controls.append(status,button);row.append(details,controls);playerList.append(row);
  });
}
async function loadPlayers(){const {data,error}=await supabase.from("profiles").select("id,email,display_name,first_name,last_name,approved,is_admin,created_at").order("created_at",{ascending:false});if(error){message.textContent=`Couldn’t load players: ${error.message}`;return}allPlayers=data;renderPlayers(allPlayers)}
async function setApproval(player,newApproved,button){button.disabled=true;message.textContent=`${newApproved?"Approving":"Revoking access for"} ${playerName(player)}…`;const {error}=await supabase.rpc("set_player_approval",{player_id:player.id,new_approved:newApproved});if(error){button.disabled=false;message.textContent=error.message;return}message.textContent=`${playerName(player)} is now ${newApproved?"approved":"waiting for approval"}.`;await loadPlayers()}
function renderPotPlayerOptions(){potPlayerOptions.replaceChildren();const approved=allPlayers.filter(player=>player.approved);if(!approved.length){potPlayerOptions.textContent="Approve at least one player before creating a pot.";return}approved.forEach(player=>{const label=document.createElement("label");label.className="check-option";const input=document.createElement("input");input.type="checkbox";input.name="playerIds";input.value=player.id;const text=document.createElement("span");text.innerHTML=`<strong>${playerName(player)}</strong><small>${player.email}</small>`;label.append(input,text);potPlayerOptions.append(label)})}
function buildGameweekGrid(){for(let gameweek=1;gameweek<=38;gameweek+=1){const label=document.createElement("label");label.className="gameweek-option";const input=document.createElement("input");input.type="radio";input.name="startGameweek";input.value=String(gameweek);input.required=true;const text=document.createElement("span");text.textContent=`GW${gameweek}`;label.append(input,text);gameweekGrid.append(label)}}
function money(pence){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(pence/100)}
function paymentLabel(status){return status==="paid"?"Paid":status==="claimed"?"Player says paid":"Not paid"}
function renderPots(pots,gameweeks,members){potList.replaceChildren();playerCount.textContent=pots.length;countLabel.textContent=pots.length===1?"pot":"pots";if(!pots.length){const empty=document.createElement("p");empty.className="empty-list";empty.textContent="No pots yet. Create your first draft pot above.";potList.append(empty);return}pots.forEach(pot=>{const potGameweeks=gameweeks.filter(item=>item.pot_id===pot.id).map(item=>item.gameweek_number).sort((a,b)=>a-b);const potMembers=members.filter(item=>item.pot_id===pot.id);const card=document.createElement("article");card.className="pot-card";const heading=document.createElement("header");heading.innerHTML=`<div><span class="status pending">${pot.status}</span><h2>${pot.name}</h2><p>${pot.season} · ${money(pot.entry_fee_pence)} entry · ${money(pot.buy_back_fee_pence)} buy-back</p></div><strong>${potMembers.length} player${potMembers.length===1?"":"s"}</strong>`;const weeks=document.createElement("div");weeks.className="pot-weeks";const weekText=document.createElement("span");weekText.textContent=potGameweeks.map(gw=>`GW${gw}`).join(" · ");weeks.append(weekText);if(potGameweeks.length&&potGameweeks.at(-1)<38){const fillButton=document.createElement("button");fillButton.type="button";fillButton.className="fill-weeks-button";fillButton.textContent="Include through GW38";fillButton.addEventListener("click",()=>fillRemainingGameweeks(pot.id,fillButton));weeks.append(fillButton)}const memberList=document.createElement("div");memberList.className="pot-member-list";potMembers.forEach(member=>{const player=allPlayers.find(item=>item.id===member.player_id);const row=document.createElement("div");row.className="pot-member";const details=document.createElement("span");details.innerHTML=`<strong>${player?playerName(player):"Unknown player"}</strong><small>${player?.email||""}</small>`;const select=document.createElement("select");select.setAttribute("aria-label",`Payment status for ${player?playerName(player):"player"}`);[["unpaid","Not paid"],["claimed","Player says paid"],["paid","Paid"]].forEach(([value,label])=>{const option=document.createElement("option");option.value=value;option.textContent=label;option.selected=member.payment_status===value;select.append(option)});select.addEventListener("change",()=>setPayment(pot.id,member.player_id,select));row.append(details,select);memberList.append(row)});card.append(heading,weeks,memberList);potList.append(card)})}
async function fillRemainingGameweeks(potId,button){button.disabled=true;message.textContent="Adding the remaining gameweeks…";const {error}=await supabase.rpc("fill_remaining_pot_gameweeks",{selected_pot_id:potId});if(error){button.disabled=false;message.textContent=`${error.message}. Run 08 — Automatic remaining gameweeks in Supabase.`;return}message.textContent="The pot now includes every remaining gameweek through GW38.";await loadPots()}
async function loadPots(){message.textContent="Loading pots…";const [potsResult,weeksResult,membersResult]=await Promise.all([supabase.from("pots").select("*").order("created_at",{ascending:false}),supabase.from("pot_gameweeks").select("pot_id,gameweek_number"),supabase.from("pot_players").select("pot_id,player_id,payment_status,player_status,buy_back_status")]);const error=potsResult.error||weeksResult.error||membersResult.error;if(error){message.textContent=`Couldn’t load pots: ${error.message}. Run 06 — Pot and payment setup in Supabase.`;return}message.textContent="";renderPots(potsResult.data,weeksResult.data,membersResult.data)}
async function setPayment(potId,playerId,select){select.disabled=true;message.textContent=`Saving payment as “${paymentLabel(select.value)}”…`;const {error}=await supabase.rpc("set_pot_player_payment",{selected_pot_id:potId,selected_player_id:playerId,new_payment_status:select.value});select.disabled=false;if(error){message.textContent=error.message;await loadPots();return}message.textContent="Payment status saved."}
function fixtureTeam(team,isAway=false){const wrapper=document.createElement("div");wrapper.className=`fixture-team${isAway?" away":""}`;const image=document.createElement("img");image.src=team.emblem_url||"";image.alt="";const name=document.createElement("span");name.textContent=team.short_name;if(isAway)wrapper.append(name,image);else wrapper.append(image,name);return wrapper}
function renderFixtures(fixtures,teams){fixtureList.replaceChildren();playerCount.textContent=fixtures.length;countLabel.textContent=fixtures.length===1?"fixture":"fixtures";if(!fixtures.length){const empty=document.createElement("p");empty.className="fixture-empty";empty.textContent="No fixtures imported yet. Use Sync FPL data above.";fixtureList.append(empty);return}const teamMap=new Map(teams.map(team=>[team.id,team]));fixtures.slice(0,30).forEach(fixture=>{const home=teamMap.get(fixture.home_team_id),away=teamMap.get(fixture.away_team_id);if(!home||!away)return;const row=document.createElement("article");row.className="fixture-row";const gameweek=document.createElement("span");gameweek.className="fixture-gameweek";gameweek.textContent=fixture.gameweek_number?`GW${fixture.gameweek_number}`:"TBC";const score=document.createElement("strong");score.className="fixture-score";score.textContent=fixture.finished?`${fixture.home_score} – ${fixture.away_score}`:"v";const time=document.createElement("time");time.className="fixture-time";if(fixture.kickoff_at){const kickoff=new Date(fixture.kickoff_at);time.dateTime=fixture.kickoff_at;time.textContent=kickoff.toLocaleString("en-GB",{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}else time.textContent="Time TBC";row.append(gameweek,fixtureTeam(home),score,fixtureTeam(away,true),time);fixtureList.append(row)})}
async function loadFixtures(){message.textContent="Loading fixtures…";const [fixturesResult,teamsResult]=await Promise.all([supabase.from("football_fixtures").select("*").eq("season",CURRENT_SEASON).order("kickoff_at",{ascending:true,nullsFirst:false}),supabase.from("football_teams").select("id,name,short_name,emblem_url")]);const error=fixturesResult.error||teamsResult.error;if(error){message.textContent=`Couldn’t load fixtures: ${error.message}. Run 09 — FPL clubs and fixture import in Supabase.`;fixtureList.replaceChildren();return}message.textContent="";fixtureSyncDetail.textContent=fixturesResult.data.length?`${fixturesResult.data.length} fixtures saved for ${CURRENT_SEASON}. The list below shows the first 30.`:"No football data has been synced yet.";renderFixtures(fixturesResult.data,teamsResult.data)}
async function syncFplData(){syncFplButton.disabled=true;message.textContent="Downloading the latest FPL clubs and fixtures…";try{const [bootstrapResponse,fixturesResponse]=await Promise.all([fetch("https://fantasy.premierleague.com/api/bootstrap-static/"),fetch("https://fantasy.premierleague.com/api/fixtures/")]);if(!bootstrapResponse.ok||!fixturesResponse.ok)throw new Error("The FPL feed did not respond. Try again shortly.");const [bootstrap,fixtures]=await Promise.all([bootstrapResponse.json(),fixturesResponse.json()]);const {data,error}=await supabase.rpc("sync_fpl_data",{selected_season:CURRENT_SEASON,fpl_teams:bootstrap.teams,fpl_fixtures:fixtures});if(error)throw error;message.textContent=`FPL sync complete: ${data.teams} clubs and ${data.fixtures} fixtures updated.`;await loadFixtures()}catch(error){message.textContent=`Couldn’t sync FPL data: ${error.message}`}finally{syncFplButton.disabled=false}}
function switchView(view){playersView.hidden=view!=="players";potsView.hidden=view!=="pots";fixturesView.hidden=view!=="fixtures";adminTitle.textContent=view==="pots"?"Pots":view==="fixtures"?"Fixtures":"Players";document.querySelectorAll(".admin-tab").forEach(tab=>tab.classList.toggle("active",tab.dataset.view===view));if(view==="pots"){renderPotPlayerOptions();loadPots()}else if(view==="fixtures")loadFixtures();else{playerCount.textContent=allPlayers.length;countLabel.textContent="registered"}}
async function initialise(){const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace("/");return}const {data:isAdmin,error}=await supabase.rpc("is_current_user_admin");if(error){loading.hidden=true;denied.hidden=false;denied.querySelector(".intro").textContent=`Admin check failed: ${error.message}`;return}if(!isAdmin){showDenied();return}loading.hidden=true;content.hidden=false;const {data,error:playersError}=await supabase.from("profiles").select("id,email,display_name,first_name,last_name,approved,is_admin,created_at").order("created_at",{ascending:false});if(playersError){message.textContent=`Couldn’t load players: ${playersError.message}`;return}allPlayers=data;renderPlayers(allPlayers);buildGameweekGrid()}
document.querySelectorAll(".admin-tab").forEach(tab=>tab.addEventListener("click",()=>switchView(tab.dataset.view)));
showPotFormButton.addEventListener("click",()=>{potForm.hidden=false;showPotFormButton.hidden=true;potForm.querySelector("input").focus()});
cancelPotButton.addEventListener("click",()=>{potForm.hidden=true;showPotFormButton.hidden=false});
potForm.addEventListener("submit",async event=>{event.preventDefault();const submit=potForm.querySelector("button[type='submit']"),data=new FormData(potForm),startGameweek=Number(data.get("startGameweek")),playerIds=data.getAll("playerIds");if(!startGameweek){message.textContent="Select the starting gameweek.";return}if(!playerIds.length){message.textContent="Assign at least one approved player.";return}const gameweeks=Array.from({length:39-startGameweek},(_,index)=>startGameweek+index);submit.disabled=true;message.textContent="Creating the pot…";const poundsToPence=value=>Math.round(Number(value)*100);const {error}=await supabase.rpc("create_pot",{pot_name:data.get("potName"),pot_season:data.get("season"),entry_fee_pence:poundsToPence(data.get("entryFee")),buy_back_fee_pence:poundsToPence(data.get("buyBackFee")),gameweek_numbers:gameweeks,player_ids:playerIds});submit.disabled=false;if(error){message.textContent=error.message;return}potForm.reset();potForm.querySelector("[name='season']").value="2026/27";potForm.querySelector("[name='entryFee']").value="10";potForm.querySelector("[name='buyBackFee']").value="10";potForm.hidden=true;showPotFormButton.hidden=false;message.textContent="Draft pot created with every gameweek through GW38.";await loadPots()});
signOutButton.addEventListener("click",async()=>{signOutButton.disabled=true;await supabase.auth.signOut();window.location.replace("/")});initialise();
syncFplButton.addEventListener("click",syncFplData);
