import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const loading=document.querySelector("#dashboard-loading"),empty=document.querySelector("#dashboard-empty"),content=document.querySelector("#dashboard-content"),potsContainer=document.querySelector("#dashboard-pots"),greeting=document.querySelector("#dashboard-greeting"),message=document.querySelector("#dashboard-message"),signOutButton=document.querySelector("#sign-out"),adminLink=document.querySelector("#admin-link");
const money=pence=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(pence/100);
const paymentCopy=status=>status==="paid"?["Paid","Your payment has been confirmed by the admin."]:status==="claimed"?["Awaiting confirmation","You’ve marked this as paid. The admin will confirm it."]:["Payment due","Pay the admin, then let them know using the button."];

function addText(parent,tag,text,className){const element=document.createElement(tag);if(className)element.className=className;element.textContent=text;parent.append(element);return element}
function renderPot(pot){const card=document.createElement("article");card.className="dashboard-pot";const header=document.createElement("header");header.className="dashboard-pot-header";const title=document.createElement("div");addText(title,"p",`${pot.season} · ${pot.status}`,"label");addText(title,"h2",pot.name);addText(title,"p",`${money(pot.entry_fee_pence)} entry · ${money(pot.buy_back_fee_pence)} one-time buy-back`);addText(header,"span",pot.player_status,"pot-player-status");header.prepend(title);
  const summary=document.createElement("div");summary.className="dashboard-summary";[["Player status",pot.player_status],["Payment",paymentCopy(pot.payment_status)[0]],["Buy-back",pot.buy_back_status]].forEach(([label,value])=>{const item=document.createElement("div");item.className="summary-item";addText(item,"span",label);addText(item,"strong",value);summary.append(item)});
  const payment=document.createElement("div");payment.className="payment-panel";const paymentText=document.createElement("div");const [statusLabel,statusDescription]=paymentCopy(pot.payment_status);addText(paymentText,"strong",statusLabel,`payment-status ${pot.payment_status}`);addText(paymentText,"p",statusDescription);payment.append(paymentText);if(pot.payment_status==="unpaid"){const button=addText(payment,"button","I’ve paid","claim-button");button.type="button";button.addEventListener("click",()=>claimPayment(pot.id,button))}
  const gameweeks=document.createElement("section");gameweeks.className="pot-gameweeks";addText(gameweeks,"h3","Included gameweeks");const chips=document.createElement("div");chips.className="gameweek-chips";(pot.gameweeks||[]).forEach(gameweek=>addText(chips,"span",`GW${gameweek}`,"gameweek-chip"));gameweeks.append(chips);
  const next=document.createElement("section");next.className="next-stage";addText(next,"h3","Team selection coming next");const nextText=document.createElement("p");nextText.append("Once fixtures are connected, this area will show your available teams and upcoming matches. ");addText(nextText,"strong","Your pot membership and payment tracking are already live.");next.append(nextText);
  card.append(header,summary,payment,gameweeks,next);potsContainer.append(card)}
async function loadDashboard(){const {data,error}=await supabase.rpc("get_my_dashboard");if(error){loading.querySelector("h1").textContent="Couldn’t load your dashboard.";const detail=addText(loading,"p",error.message,"intro");detail.style.fontSize=".9rem";return}if(!data?.approved||!data?.pots?.length){loading.hidden=true;empty.hidden=false;return}loading.hidden=true;content.hidden=false;greeting.textContent=data.first_name?`${data.first_name}’s pots`:"Your pots";potsContainer.replaceChildren();data.pots.forEach(renderPot)}
async function claimPayment(potId,button){button.disabled=true;message.textContent="Saving your payment claim…";const {error}=await supabase.rpc("claim_pot_payment",{selected_pot_id:potId});if(error){button.disabled=false;message.textContent=error.message;return}message.textContent="Payment marked as sent. The admin can now confirm it.";await loadDashboard()}
async function initialise(){const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace("/");return}const {data:isAdmin}=await supabase.rpc("is_current_user_admin");adminLink.hidden=!isAdmin;await loadDashboard()}
signOutButton.addEventListener("click",async()=>{signOutButton.disabled=true;await supabase.auth.signOut();window.location.replace("/")});initialise();
