import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const loading=document.querySelector("#dashboard-loading"),empty=document.querySelector("#dashboard-empty"),content=document.querySelector("#dashboard-content"),potsContainer=document.querySelector("#dashboard-pots"),greeting=document.querySelector("#dashboard-greeting"),potCount=document.querySelector("#pot-count"),message=document.querySelector("#dashboard-message"),signOutButton=document.querySelector("#sign-out"),adminLink=document.querySelector("#admin-link"),accountIdentity=document.querySelector("#account-identity"),accountName=document.querySelector("#account-name"),accountEmail=document.querySelector("#account-email");
const money=pence=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(pence/100);
const paymentCopy=status=>status==="paid"?["Paid","Your payment has been confirmed by the admin."]:status==="claimed"?["Awaiting confirmation","You’ve marked this as paid. The admin will confirm it."]:["Payment due","Pay the admin, then let them know using the button."];

function addText(parent,tag,text,className){const element=document.createElement(tag);if(className)element.className=className;element.textContent=text;parent.append(element);return element}
function formDots(team){const form=document.createElement("div");form.className="form-dots";(team.form||[]).forEach(result=>addText(form,"span",result,`form-dot ${result}`));return form}
function teamButton(team,fixture,pot,selection,isAway=false){const button=document.createElement("button");button.type="button";button.className=`pick-team${isAway?" away":""}`;const image=document.createElement("img");image.src=team.emblem_url||"";image.alt="";const copy=document.createElement("span");copy.className="pick-team-copy";addText(copy,"strong",team.name);copy.append(formDots(team));if(!team.available)addText(copy,"small","Already used");button.append(image,copy);button.disabled=selection.payment_status!=="paid"||selection.player_status!=="active"||!team.available||new Date(fixture.kickoff_at)<=new Date()||fixture.started||fixture.finished;button.addEventListener("click",()=>confirmPick(pot,fixture,team,button));return button}
function renderSelection(pot,selection,panel){panel.replaceChildren();const heading=document.createElement("div");heading.className="selection-heading";const title=document.createElement("div");addText(title,"p","MAKE YOUR PICK","label");addText(title,"h3",selection.gameweek_number?`Gameweek ${selection.gameweek_number}`:"No upcoming gameweek");addText(heading,"span",`${selection.remaining_teams?.length||0} teams remaining`,"remaining-count");heading.prepend(title);panel.append(heading);
  if(selection.pick){const locked=document.createElement("div");locked.className="locked-pick";const image=document.createElement("img");image.src=selection.pick.emblem_url||"";image.alt="";const copy=document.createElement("div");addText(copy,"span",`GW${selection.pick.gameweek_number} PICK`,`label`);addText(copy,"h4",selection.pick.team_name);addText(copy,"p",`${selection.pick.home_name} v ${selection.pick.away_name} · ${new Date(selection.pick.kickoff_at).toLocaleString("en-GB",{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}`);locked.append(image,copy);addText(locked,"span","Locked","locked-mark");panel.append(locked);return}
  if(!selection.gameweek_number){addText(panel,"p","There are no upcoming fixtures in this pot yet.","selection-note");return}
  if(selection.payment_status!=="paid")addText(panel,"p","You can review the fixtures now. Team selection unlocks after the admin confirms your entry payment.","selection-note warning");
  const grouped=new Map();(selection.fixtures||[]).forEach(fixture=>{const day=fixture.kickoff_at?new Date(fixture.kickoff_at).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"}):"Date to be confirmed";if(!grouped.has(day))grouped.set(day,[]);grouped.get(day).push(fixture)});grouped.forEach((fixtures,day)=>{const section=document.createElement("section");section.className="fixture-day";addText(section,"h4",day,"fixture-day-title");fixtures.forEach(fixture=>{const row=document.createElement("div");row.className="pick-fixture";const centre=document.createElement("div");centre.className="fixture-centre";const kickoff=fixture.kickoff_at?new Date(fixture.kickoff_at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"}):"TBC";addText(centre,"b",fixture.finished?`${fixture.home_score} – ${fixture.away_score}`:kickoff);addText(centre,"span",fixture.finished?"Full time":fixture.started?"Started":"Kickoff");row.append(teamButton(fixture.home_team,fixture,pot,selection),centre,teamButton(fixture.away_team,fixture,pot,selection,true));section.append(row)});panel.append(section)});
  const remaining=document.createElement("div");remaining.className="remaining-clubs";(selection.remaining_teams||[]).forEach(team=>{const club=document.createElement("span");club.className="remaining-club";const image=document.createElement("img");image.src=team.emblem_url||"";image.alt="";club.append(image,document.createTextNode(team.short_name));remaining.append(club)});panel.append(remaining)}
async function loadPotSelection(pot,panel){const {data,error}=await supabase.rpc("get_pot_selection",{selected_pot_id:pot.id});if(error){panel.replaceChildren();addText(panel,"p",`Team selection isn’t ready: ${error.message}. Run 10 — Player fixture selection and locked picks in Supabase.`,"selection-note warning");return}renderSelection(pot,data,panel)}
async function confirmPick(pot,fixture,team,button){const kickoff=new Date(fixture.kickoff_at).toLocaleString("en-GB",{weekday:"long",day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"});if(!window.confirm(`Lock in ${team.name} for ${pot.name}?\n\n${fixture.home_team.name} v ${fixture.away_team.name}\n${kickoff}\n\nThis cannot be changed.`))return;button.disabled=true;message.textContent=`Locking in ${team.name}…`;const {error}=await supabase.rpc("confirm_team_pick",{selected_pot_id:pot.id,selected_fixture_id:fixture.id,selected_team_id:team.id});if(error){message.textContent=error.message;button.disabled=false;return}message.textContent=`${team.name} is confirmed and locked.`;await loadDashboard()}
function renderPot(pot){const card=document.createElement("article");card.className="dashboard-pot";const header=document.createElement("header");header.className="dashboard-pot-header";const title=document.createElement("div");addText(title,"p",`${pot.season} · ${pot.status}`,"label");addText(title,"h2",pot.name);addText(title,"p",`${money(pot.entry_fee_pence)} entry · ${money(pot.buy_back_fee_pence)} one-time buy-back`);addText(header,"span",pot.player_status,"pot-player-status");header.prepend(title);
  const summary=document.createElement("div");summary.className="dashboard-summary";[["Player status",pot.player_status],["Payment",paymentCopy(pot.payment_status)[0]],["Buy-back",pot.buy_back_status]].forEach(([label,value])=>{const item=document.createElement("div");item.className="summary-item";addText(item,"span",label);addText(item,"strong",value);summary.append(item)});
  const payment=document.createElement("div");payment.className="payment-panel";const paymentText=document.createElement("div");const [statusLabel,statusDescription]=paymentCopy(pot.payment_status);addText(paymentText,"strong",statusLabel,`payment-status ${pot.payment_status}`);addText(paymentText,"p",statusDescription);payment.append(paymentText);if(pot.payment_status==="unpaid"){const button=addText(payment,"button","I’ve paid","claim-button");button.type="button";button.addEventListener("click",()=>claimPayment(pot.id,button))}
  const gameweeks=document.createElement("section");gameweeks.className="pot-gameweeks";addText(gameweeks,"h3","Included gameweeks");const chips=document.createElement("div");chips.className="gameweek-chips";const included=pot.gameweeks||[];if(included.length){const first=included[0],last=included.at(-1),label=first===last?`GW${first}`:`GW${first} → GW${last} · ${included.length} gameweeks`;addText(chips,"span",label,"gameweek-chip")}gameweeks.append(chips);
  const selection=document.createElement("section");selection.className="selection-panel";addText(selection,"p","Loading fixtures…","selection-note");card.append(header,summary,payment,gameweeks,selection);potsContainer.append(card);loadPotSelection(pot,selection)}
async function loadDashboard(){const {data,error}=await supabase.rpc("get_my_dashboard");if(error){loading.querySelector("h1").textContent="Couldn’t load your dashboard.";const detail=addText(loading,"p",error.message,"intro");detail.style.fontSize=".9rem";return}if(data?.email){accountName.textContent=data.first_name||"Player";accountEmail.textContent=data.email;accountIdentity.hidden=false}if(!data?.approved||!data?.pots?.length){loading.hidden=true;empty.hidden=false;return}loading.hidden=true;content.hidden=false;greeting.textContent="Last Man Standing 26/27 Pots";potCount.textContent=`${data.pots.length} pot${data.pots.length===1?"":"s"}`;potsContainer.replaceChildren();data.pots.forEach(renderPot)}
async function claimPayment(potId,button){button.disabled=true;message.textContent="Saving your payment claim…";const {error}=await supabase.rpc("claim_pot_payment",{selected_pot_id:potId});if(error){button.disabled=false;message.textContent=error.message;return}message.textContent="Payment marked as sent. The admin can now confirm it.";await loadDashboard()}
async function initialise(){const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace("/");return}const {data:isAdmin}=await supabase.rpc("is_current_user_admin");adminLink.hidden=!isAdmin;await loadDashboard()}
signOutButton.addEventListener("click",async()=>{signOutButton.disabled=true;await supabase.auth.signOut();window.location.replace("/")});initialise();
