import { JSDOM } from 'jsdom';
import { beforeEach, afterEach, expect, it, vi } from 'vitest';
let openReasonDialog, renderPlayerMemberships, renderAvailablePots;
let dom;
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
const click=text=>[...document.querySelectorAll('button')].find(b=>b.textContent===text).click();
beforeEach(async()=>{dom=new JSDOM('<main></main>');vi.stubGlobal('window',dom.window);vi.stubGlobal('document',dom.window.document);vi.stubGlobal('Option',dom.window.Option);dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};({openReasonDialog}=await import("../reason-dialog.js"));({renderPlayerMemberships,renderAvailablePots}=await import("../membership-ui.js"));});
afterEach(()=>{dom.window.close();vi.unstubAllGlobals();});
function dialogue(overrides={}){const options={title:'Resolve review',explanation:'Keep the existing winners.',loadPreview:vi.fn(async()=>({version_token:'v1'})),submit:vi.fn(async()=>{}),onSuccess:vi.fn(async()=>{}),...overrides};const dialog=openReasonDialog(options);return {...options,dialog};}
function submit(reason){document.querySelector('textarea').value=reason;document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));}
it('cancels without submitting or resolving the review',async()=>{const d=dialogue();await flush();click('Cancel');expect(document.querySelector('dialog')).toBeNull();expect(d.submit).not.toHaveBeenCalled();});
it('validates trimmed reason before sending the current preview',async()=>{const d=dialogue();await flush();submit('    short   ');await flush();expect(d.submit).not.toHaveBeenCalled();expect(d.dialog.textContent).toContain('10–1000');submit('  Reviewed the final results.  ');await flush();expect(d.submit).toHaveBeenCalledWith('Reviewed the final results.',{version_token:'v1'});expect(d.onSuccess).toHaveBeenCalledOnce();expect(document.querySelector('dialog')).toBeNull();});
it('blocks duplicate submissions and cancellation while saving',async()=>{const pending=deferred();const d=dialogue({submit:vi.fn(()=>pending.promise)});await flush();submit('Verified final outcomes.');submit('Verified final outcomes.');click('Cancel');expect(d.submit).toHaveBeenCalledOnce();expect(d.dialog.open).toBe(true);expect(document.querySelector('textarea').disabled).toBe(true);pending.resolve();await flush();expect(document.querySelector('dialog')).toBeNull();});
it('retains failed input and requires a fresh preview after stale review state',async()=>{const d=dialogue({submit:vi.fn().mockRejectedValueOnce(new Error('Review state changed; refresh and try again')).mockResolvedValueOnce(null)});await flush();submit('Verified final outcomes.');await flush();expect(document.querySelector('textarea').value).toBe('Verified final outcomes.');expect([...document.querySelectorAll('button')].find(b=>b.textContent==='Confirm resolution').disabled).toBe(true);d.loadPreview.mockResolvedValue({version_token:'v2'});click('Refresh preview');await flush();submit('Verified final outcomes.');await flush();expect(d.submit).toHaveBeenLastCalledWith('Verified final outcomes.',{version_token:'v2'});});
it('shows preview failure and allows cancellation without mutation',async()=>{const d=dialogue({loadPreview:vi.fn(async()=>{throw new Error('Preview unavailable');})});await flush();expect(d.dialog.textContent).toContain('Preview unavailable');click('Cancel');expect(d.submit).not.toHaveBeenCalled();});
const player={id:'alice',name:'Alice',email:'alice@example.test'};
const membership=(id,payment='unpaid')=>({pot_id:id,name:id,season:'2026',pot_status:'open',player_status:'active',payment_status:payment,buy_back_status:'requested',buy_back_payment_status:'unpaid',buy_back_fee_pence:500});
const data={memberships:[membership('Pot A','paid'),membership('Pot B')],requests:[{pot_id:'Pot C',player_id:'alice',name:'Pot C',status:'pending',version:3}],assignable_pots:[{id:'Pot D',name:'Pot D',season:'2026'}]};
function clientFor(value=data){return {rpc:vi.fn(async name=>({data:name==='get_admin_player_memberships'?value:null}))};}
it('changes only the selected pot entry payment for the selected player',async()=>{const client=clientFor();await renderPlayerMemberships(document.querySelector('main'),player,client);const select=document.querySelector('[aria-label="Entry payment for Pot B"]');select.value='paid';[...select.closest('article').querySelectorAll('button')][0].click();await flush();expect(client.rpc).toHaveBeenCalledWith('set_pot_player_payment',{selected_pot_id:'Pot B',selected_player_id:'alice',new_payment_status:'paid'});});
it('confirms buy-back payment through the existing pot-specific RPC',async()=>{const client=clientFor();await renderPlayerMemberships(document.querySelector('main'),player,client);click('Confirm £5.00 buy-back payment');await flush();expect(client.rpc).toHaveBeenCalledWith('set_buy_back_decision',{selected_pot_id:'Pot A',selected_player_id:'alice',approved:true});});
it.each([['Accept request',true],['Decline request',false]])('sends versioned %s to the request owner and pot',async(label,accept)=>{const client=clientFor();await renderPlayerMemberships(document.querySelector('main'),player,client);click(label);await flush();expect(client.rpc).toHaveBeenCalledWith('decide_pot_membership',{selected_pot_id:'Pot C',selected_player_id:'alice',expected_version:3,accept_request:accept});});
it('assigns the selected player without inventing another membership model',async()=>{const client=clientFor();await renderPlayerMemberships(document.querySelector('main'),player,client);document.querySelector('[aria-label="Assign Alice to a pot"]').value='Pot D';click('Assign player');await flush();expect(client.rpc).toHaveBeenCalledWith('add_player_to_pot',{selected_pot_id:'Pot D',selected_player_id:'alice'});});
it('ignores a previous player load that finishes after the new selection',async()=>{const pending=deferred(),client=clientFor({memberships:[],requests:[],assignable_pots:[]});client.rpc.mockImplementationOnce(()=>pending.promise);const target=document.querySelector('main');const first=renderPlayerMemberships(target,player,client);await renderPlayerMemberships(target,{...player,id:'bob',name:'Bob'},client);pending.resolve({data});await first;expect(target.textContent).toContain('Bob — pot memberships');expect(target.textContent).not.toContain('Pot A');});
it('does not return to the previous player when their payment save finishes',async()=>{const pending=deferred(),client=clientFor();const target=document.querySelector('main');await renderPlayerMemberships(target,player,client);client.rpc.mockImplementationOnce(()=>pending.promise);click('Save entry payment');await renderPlayerMemberships(target,{...player,id:'bob',name:'Bob'},client);pending.resolve({data:null});await flush();expect(target.querySelector('h2').textContent).toContain('Bob');});
it('renders declined, pending and unavailable states with only eligible request actions',async()=>{const client=clientFor(),refresh=vi.fn();renderAvailablePots(document.querySelector('main'),['declined','pending','unavailable'].map((state,i)=>({id:String(i),name:state,state,entry_fee_pence:100,buy_back_fee_pence:50,request_status:'pending'})),client,refresh);expect(document.querySelectorAll('button')).toHaveLength(1);click('Request again');await flush();expect(client.rpc).toHaveBeenCalledWith('request_pot_membership',{selected_pot_id:'0'});expect(refresh).toHaveBeenCalledOnce();});
it('allows cancellation while the read-only preview is still loading',async()=>{const pending=deferred();const d=dialogue({loadPreview:()=>pending.promise});click('Cancel');expect(document.querySelector('dialog')).toBeNull();pending.resolve({version_token:'late'});await flush();expect(document.querySelector('dialog')).toBeNull();expect(d.submit).not.toHaveBeenCalled();});
